Add initial module passing all tests
cloudeteer/terraform-azurerm-mssql-vm pull request #3
Opened 2024-12-16 13:48 UTC by rswrz

This PR adds a basic first module for Azure MSSQL on Virtual Machine. The aim is not to have a production-ready module, but a first v0 release.

2024-12-17 08:41 UTC, rswrz commented on tests/local/input_sotrage_configuration.tftest.hcl
> +}
> [!NOTE]
> Whoever reviews this, allow me to explain, why this is important and relevant to all modules we use in a module.

2025-01-14 16:00 UTC, lixhunter requested changes

2025-01-14 16:00 UTC, lixhunter commented on tests/local/input_sotrage_configuration.tftest.hcl
file name is wrong

2025-01-14 16:00 UTC, lixhunter commented on tests/local/input_sotrage_configuration.tftest.hcl
> +}
I do not understand the testcase. The Paths seems to be valid from test parameter point of view. If the Test ist valid, please add a description to the method or the parameter what should lead to the failure.

2025-01-14 16:00 UTC, lixhunter commented on tests/local/input_sotrage_configuration.tftest.hcl
> +}
"should_fail_" may be a oversight. Please choose a name to describe what is tested here.

2025-01-14 16:00 UTC, lixhunter commented on variables.tf
> +  #   }
Comments in examples are OK, when referenced in the Readme. Otherwise remove commented code.

2025-01-14 16:00 UTC, lixhunter commented on variables.tf
> +  #   }
Comments in examples are OK, when referenced in the Readme. Otherwise remove commented code.

2025-01-14 16:00 UTC, lixhunter commented on variables.tf
> +  # }
Comments in examples are OK, when referenced in the Readme. Otherwise remove commented code.

2025-01-14 16:00 UTC, lixhunter commented on main.tf
> +  #   }
Comments in examples are OK, when referenced in the Readme. Otherwise remove commented code.

2025-01-31 10:09 UTC, rswrz commented on tests/local/input_sotrage_configuration.tftest.hcl
> +}
Renamed the test and added a short comment on the section of the complex variabke which leads to an error.

2025-01-31 10:09 UTC, rswrz commented on tests/local/input_sotrage_configuration.tftest.hcl
File renamed, thanks!

2025-01-31 10:11 UTC, rswrz commented on tests/local/input_sotrage_configuration.tftest.hcl
> +}
Test has been renamed.

2025-01-31 10:13 UTC, rswrz commented on variables.tf
> +  #   }
Comment removed

2025-01-31 10:14 UTC, rswrz commented on variables.tf
> +  #   }
Comment removed

2025-01-31 10:14 UTC, rswrz commented on variables.tf
> +  # }
Comment removed

2025-01-31 10:14 UTC, rswrz commented on main.tf
> +  #   }
Comment removed

2025-01-31 10:16 UTC, rswrz commented
Thanks for reviewing this, @lixhunter! I appreciate your feedback and apologize for the delay in implementing your suggestions.

2025-02-11 13:11 UTC, lixhunter approved these changes

2025-02-11 13:41 UTC, merged